# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/vga_initials/Basys-3-Master.xdc

# Block Designs: bd/rom_640x480/rom_640x480.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rom_640x480 || ORIG_REF_NAME==rom_640x480} -quiet] -quiet

# IP: bd/rom_640x480/ip/rom_640x480_dist_mem_gen_0_0/rom_640x480_dist_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rom_640x480_dist_mem_gen_0_0 || ORIG_REF_NAME==rom_640x480_dist_mem_gen_0_0} -quiet] -quiet

# XDC: c:/repo/my-vhdl-code/vga_distram/vga_distram.gen/sources_1/bd/rom_640x480/rom_640x480_ooc.xdc
