#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Wed Sep 29 14:07:56 CDT 2021
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto dd2f1ef6ad2e4a41999ec70655ca3b97 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot comparador_4b_tb_behav xil_defaultlib.comparador_4b_tb -log elaborate.log"
xelab -wto dd2f1ef6ad2e4a41999ec70655ca3b97 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot comparador_4b_tb_behav xil_defaultlib.comparador_4b_tb -log elaborate.log

